spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@172.18.1.3:1521:orcl
    username: fulin
    password: fulin123

mybatis:
  mapper-locations: classpath*:/mapper/*.xml

logging:
  level:
    root: info