server:
  port: 1001
spring:
  application:
    name: springboot_demo
  thymeleaf:
    cache: false
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath*:/mapper/*.xml

## 日志级别设置
#logging:
#  level:
#    com.fanciter: DEBUG