server:
  port: 1001
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: springcloud_demo
  datasource:
    testdata:
      username: fulin
      password : fulin~Fulin
      masterUrl: jdbc:mysql://localhost:3306/test?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
      secondUrl: jdbc:mysql://localhost:3306/test2?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
      driverClassName: com.mysql.jdbc.Driver


#master:
#  datasource:
#    url: jdbc:mysql://localhost:3306/test?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
#    username: root
#    password: root
#    driverClassName: com.mysql.jdbc.Driver
#second:
#  datasource:
#    url: jdbc:mysql://localhost:3306/test2?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
#    username: root
#    password: root
#    driverClassName: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath*:/mapper/*.xml

## 日志级别设置
#logging:
#  level:
#    com.fanciter: DEBUG